remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Kartik Lodhi"
description: "I use data and AI to drive smarter decisions."

# Optional settings
show_downloads: false           # hide default download link
# google_analytics: UA-XXXXXX   # if you have an Analytics ID
