remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Kartik Lodhi — AI & ML"
description: "AI‑powered systems, custom Transformers & robotics demos by Kartik Lodhi"

# Optional settings
show_downloads: false           # hide default download link
# google_analytics: UA-XXXXXX   # if you have an Analytics ID
